comment:
  # Include bundle analysis in PR comments
  layout: "diff, flags, files, footer"
  require_bundle_changes: true
  bundle_change_threshold: "1Kb"

# Bundle analysis configuration
bundle_analysis:
  # Post informational status with 5% threshold (default)
  warning_threshold: "5%"
  status: "informational"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
