name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build package
        run: pnpm run build
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  unit-test:
    name: Unit tests

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Run tests
        run: pnpm test:coverage
      - name: Upload coverage
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Lint
        run: pnpm run lint
  validate-api:
    name: Validate API

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build package
        run: pnpm run build
      - name: Validate API
        run: pnpm run validate-api
  publish:
    name: Publish

    runs-on: ubuntu-latest
    timeout-minutes: 15

    needs: [unit-test, validate-api, lint]

    # Only run on main branch
    if: ${{ github.ref  == 'refs/heads/main' }}

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for trusted publishing and npm provenance

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v7
      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          cache: true
      - name: Build
        run: pnpm run build
      - name: Bundle typings
        run: pnpm run validate-api
      - name: Publish
        run: pnpm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
